sudo: required
services:
  - docker

before_install:
  - docker build -t lyallsathish/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true lyallsathish/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-deploy"
  env: "Docker-react-deploy-env"
  bucket_name: "elasticbeanstalk-us-east-1-678454132925"
  bucket_path: "docker-react-deploy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
