sudo: required
services:
  - docker

before_install:
  - docker build -t lyallsathish/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true lyallsathish/docker-react npm run test -- --coverage